/*
 * Generated by JasperReports - 2015/4/29 ¤U¤È 3:14
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;



/**
 *
 */
public class billreport2__1430291661910_179452 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_reportType = null;
    private JRFillParameter parameter_JASPER_REPORT = null;
    private JRFillParameter parameter_BS = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_contactTitle = null;
    private JRFillParameter parameter_address32for = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_Billing32Period = null;
    private JRFillParameter parameter_REPORT_CONTEXT = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_InvoiceNo = null;
    private JRFillParameter parameter_contactInfo = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_Balance = null;
    private JRFillParameter parameter_Currency = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_imageName = null;
    private JRFillParameter parameter_SORT_FIELDS = null;
    private JRFillParameter parameter_Previous32Balance = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_PaymentMethod = null;
    private JRFillParameter parameter_Account32Number = null;
    private JRFillParameter parameter_customerServiceNumber = null;
    private JRFillParameter parameter_applied32date = null;
    private JRFillParameter parameter_FILTER = null;
    private JRFillParameter parameter_SUBREPORT_DIR = null;
    private JRFillParameter parameter_JASPER_REPORTS_CONTEXT = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_Statement32for = null;
    private JRFillParameter parameter_Payment32Received = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_MASTER_CURRENT_PAGE = null;
    private JRFillVariable variable_MASTER_TOTAL_PAGES = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_reportType = (JRFillParameter)pm.get("reportType");
        parameter_JASPER_REPORT = (JRFillParameter)pm.get("JASPER_REPORT");
        parameter_BS = (JRFillParameter)pm.get("BS");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_contactTitle = (JRFillParameter)pm.get("contactTitle");
        parameter_address32for = (JRFillParameter)pm.get("address for");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_Billing32Period = (JRFillParameter)pm.get("Billing Period");
        parameter_REPORT_CONTEXT = (JRFillParameter)pm.get("REPORT_CONTEXT");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_InvoiceNo = (JRFillParameter)pm.get("InvoiceNo");
        parameter_contactInfo = (JRFillParameter)pm.get("contactInfo");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_Balance = (JRFillParameter)pm.get("Balance");
        parameter_Currency = (JRFillParameter)pm.get("Currency");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_imageName = (JRFillParameter)pm.get("imageName");
        parameter_SORT_FIELDS = (JRFillParameter)pm.get("SORT_FIELDS");
        parameter_Previous32Balance = (JRFillParameter)pm.get("Previous Balance");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_PaymentMethod = (JRFillParameter)pm.get("PaymentMethod");
        parameter_Account32Number = (JRFillParameter)pm.get("Account Number");
        parameter_customerServiceNumber = (JRFillParameter)pm.get("customerServiceNumber");
        parameter_applied32date = (JRFillParameter)pm.get("applied date");
        parameter_FILTER = (JRFillParameter)pm.get("FILTER");
        parameter_SUBREPORT_DIR = (JRFillParameter)pm.get("SUBREPORT_DIR");
        parameter_JASPER_REPORTS_CONTEXT = (JRFillParameter)pm.get("JASPER_REPORTS_CONTEXT");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_Statement32for = (JRFillParameter)pm.get("Statement for");
        parameter_Payment32Received = (JRFillParameter)pm.get("Payment Received");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_MASTER_CURRENT_PAGE = (JRFillVariable)vm.get("MASTER_CURRENT_PAGE");
        variable_MASTER_TOTAL_PAGES = (JRFillVariable)vm.get("MASTER_TOTAL_PAGES");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = Double.valueOf("0.00"); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = Double.valueOf("0.00"); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = "C:\\Users\\ranger.kao\\Dropbox\\workspace\\BillReportCreater\\src\\bill\\template1\\"; //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = ((java.lang.String)parameter_Statement32for.getValue()); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = ((java.lang.String)parameter_address32for.getValue()); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "2".equals(((java.lang.String)parameter_PaymentMethod.getValue())); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==1; //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = "Currency :  "+((java.lang.String)parameter_Currency.getValue()); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = "Account Number :  "+((java.lang.String)parameter_Account32Number.getValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = "Billing Period :  "+((java.lang.String)parameter_Billing32Period.getValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==1; //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ((java.lang.Double)parameter_Payment32Received.getValue()); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((java.lang.Double)parameter_Previous32Balance.getValue()); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = ((java.lang.String)parameter_PaymentMethod.getValue()); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = ((java.lang.String)parameter_Currency.getValue()); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = ((java.lang.String)parameter_applied32date.getValue()); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = new net.sf.jasperreports.engine.data.JRBeanCollectionDataSource(((java.util.List)parameter_Balance.getValue())); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "billreport_balance.jasper"; //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue())+ ((java.lang.String)parameter_imageName.getValue()); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = ((java.lang.String)parameter_contactTitle.getValue()); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = ((java.lang.String)parameter_contactInfo.getValue()); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getValue()); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getValue()); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==1; //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==1; //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getValue())<=3; //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getValue()); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getValue())>=3; //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getValue()); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue())+ ((java.lang.String)parameter_imageName.getValue()); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getValue())>=3; //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = ((java.lang.String)parameter_customerServiceNumber.getValue()); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==1; //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = !"2".equals(((java.lang.String)parameter_PaymentMethod.getValue())); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = "2".equals(((java.lang.String)parameter_PaymentMethod.getValue())) ? "Sim2Travel (Blue Ocean Alliance & rMVNO) accepts payment by VISA or MasterCard only. Each Sim2Travel bill will be charged to the credit card that you have provided.":"Sim2Travel (Blue Ocean Alliance & rMVNO) accepts payment via bank wire transfer. The total amount due must be paid in Hong Kong Dollars (HKD) via bank wire transfer. before / on the 25 of the current month. Payment MUST include the full name and bill number. Transfer should be made directly to our billing partner Sim2Travel Inc."; //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = !"2".equals(((java.lang.String)parameter_PaymentMethod.getValue())); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = ((java.lang.String)parameter_InvoiceNo.getValue()); //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==2; //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = !"2".equals(((java.lang.String)parameter_PaymentMethod.getValue())); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = !"2".equals(((java.lang.String)parameter_PaymentMethod.getValue())); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = ((java.lang.String)parameter_InvoiceNo.getValue()); //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = "2".equals(((java.lang.String)parameter_PaymentMethod.getValue())) ? "HKNet accepts payment by VISA or MasterCard only. Each Sim2Travel bill will be charged to the credit card that you have provided.":"HKNet accepts payment via bank wire transfer. The total amount due must be paid in Hong Kong Dollars (HKD) via bank wire transfer. before / on the 25 of the current month. Payment MUST include the full name and bill number. Transfer should be made directly to our billing partner Sim2Travel Inc."; //$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = ((java.util.List)parameter_BS.getValue())!=null && ((java.util.List)parameter_BS.getValue()).size()>0; //$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()); //$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getValue()); //$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = ((java.lang.String)parameter_Statement32for.getValue()); //$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = ((java.lang.String)parameter_imageName.getValue()); //$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = ((java.lang.String)parameter_Billing32Period.getValue()); //$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = ((java.lang.String)parameter_customerServiceNumber.getValue()); //$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = ((java.lang.String)parameter_Currency.getValue()); //$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = new net.sf.jasperreports.engine.data.JRBeanCollectionDataSource(((java.util.List)parameter_BS.getValue())); //$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "billreport_detail.jasper"; //$JR_EXPR_ID=59$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = Double.valueOf("0.00"); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = Double.valueOf("0.00"); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = "C:\\Users\\ranger.kao\\Dropbox\\workspace\\BillReportCreater\\src\\bill\\template1\\"; //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = ((java.lang.String)parameter_Statement32for.getValue()); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = ((java.lang.String)parameter_address32for.getValue()); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "2".equals(((java.lang.String)parameter_PaymentMethod.getValue())); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==1; //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = "Currency :  "+((java.lang.String)parameter_Currency.getValue()); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = "Account Number :  "+((java.lang.String)parameter_Account32Number.getValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = "Billing Period :  "+((java.lang.String)parameter_Billing32Period.getValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==1; //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ((java.lang.Double)parameter_Payment32Received.getValue()); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((java.lang.Double)parameter_Previous32Balance.getValue()); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = ((java.lang.String)parameter_PaymentMethod.getValue()); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = ((java.lang.String)parameter_Currency.getValue()); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = ((java.lang.String)parameter_applied32date.getValue()); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = new net.sf.jasperreports.engine.data.JRBeanCollectionDataSource(((java.util.List)parameter_Balance.getValue())); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "billreport_balance.jasper"; //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue())+ ((java.lang.String)parameter_imageName.getValue()); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = ((java.lang.String)parameter_contactTitle.getValue()); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = ((java.lang.String)parameter_contactInfo.getValue()); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==1; //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==1; //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())<=3; //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())>=3; //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue())+ ((java.lang.String)parameter_imageName.getValue()); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())>=3; //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = ((java.lang.String)parameter_customerServiceNumber.getValue()); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==1; //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = !"2".equals(((java.lang.String)parameter_PaymentMethod.getValue())); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = "2".equals(((java.lang.String)parameter_PaymentMethod.getValue())) ? "Sim2Travel (Blue Ocean Alliance & rMVNO) accepts payment by VISA or MasterCard only. Each Sim2Travel bill will be charged to the credit card that you have provided.":"Sim2Travel (Blue Ocean Alliance & rMVNO) accepts payment via bank wire transfer. The total amount due must be paid in Hong Kong Dollars (HKD) via bank wire transfer. before / on the 25 of the current month. Payment MUST include the full name and bill number. Transfer should be made directly to our billing partner Sim2Travel Inc."; //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = !"2".equals(((java.lang.String)parameter_PaymentMethod.getValue())); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = ((java.lang.String)parameter_InvoiceNo.getValue()); //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==2; //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = !"2".equals(((java.lang.String)parameter_PaymentMethod.getValue())); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = !"2".equals(((java.lang.String)parameter_PaymentMethod.getValue())); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = ((java.lang.String)parameter_InvoiceNo.getValue()); //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = "2".equals(((java.lang.String)parameter_PaymentMethod.getValue())) ? "HKNet accepts payment by VISA or MasterCard only. Each Sim2Travel bill will be charged to the credit card that you have provided.":"HKNet accepts payment via bank wire transfer. The total amount due must be paid in Hong Kong Dollars (HKD) via bank wire transfer. before / on the 25 of the current month. Payment MUST include the full name and bill number. Transfer should be made directly to our billing partner Sim2Travel Inc."; //$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = ((java.util.List)parameter_BS.getValue())!=null && ((java.util.List)parameter_BS.getValue()).size()>0; //$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()); //$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()); //$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = ((java.lang.String)parameter_Statement32for.getValue()); //$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = ((java.lang.String)parameter_imageName.getValue()); //$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = ((java.lang.String)parameter_Billing32Period.getValue()); //$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = ((java.lang.String)parameter_customerServiceNumber.getValue()); //$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = ((java.lang.String)parameter_Currency.getValue()); //$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = new net.sf.jasperreports.engine.data.JRBeanCollectionDataSource(((java.util.List)parameter_BS.getValue())); //$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "billreport_detail.jasper"; //$JR_EXPR_ID=59$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = Double.valueOf("0.00"); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = Double.valueOf("0.00"); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = "C:\\Users\\ranger.kao\\Dropbox\\workspace\\BillReportCreater\\src\\bill\\template1\\"; //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = ((java.lang.String)parameter_Statement32for.getValue()); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = ((java.lang.String)parameter_address32for.getValue()); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "2".equals(((java.lang.String)parameter_PaymentMethod.getValue())); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==1; //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = "Currency :  "+((java.lang.String)parameter_Currency.getValue()); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = "Account Number :  "+((java.lang.String)parameter_Account32Number.getValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = "Billing Period :  "+((java.lang.String)parameter_Billing32Period.getValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==1; //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ((java.lang.Double)parameter_Payment32Received.getValue()); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((java.lang.Double)parameter_Previous32Balance.getValue()); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = ((java.lang.String)parameter_PaymentMethod.getValue()); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = ((java.lang.String)parameter_Currency.getValue()); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = ((java.lang.String)parameter_applied32date.getValue()); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = new net.sf.jasperreports.engine.data.JRBeanCollectionDataSource(((java.util.List)parameter_Balance.getValue())); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "billreport_balance.jasper"; //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue())+ ((java.lang.String)parameter_imageName.getValue()); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = ((java.lang.String)parameter_contactTitle.getValue()); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = ((java.lang.String)parameter_contactInfo.getValue()); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==1; //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==1; //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())<=3; //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())>=3; //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue())+ ((java.lang.String)parameter_imageName.getValue()); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())>=3; //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = ((java.lang.String)parameter_customerServiceNumber.getValue()); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==1; //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = !"2".equals(((java.lang.String)parameter_PaymentMethod.getValue())); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = "2".equals(((java.lang.String)parameter_PaymentMethod.getValue())) ? "Sim2Travel (Blue Ocean Alliance & rMVNO) accepts payment by VISA or MasterCard only. Each Sim2Travel bill will be charged to the credit card that you have provided.":"Sim2Travel (Blue Ocean Alliance & rMVNO) accepts payment via bank wire transfer. The total amount due must be paid in Hong Kong Dollars (HKD) via bank wire transfer. before / on the 25 of the current month. Payment MUST include the full name and bill number. Transfer should be made directly to our billing partner Sim2Travel Inc."; //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = !"2".equals(((java.lang.String)parameter_PaymentMethod.getValue())); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = ((java.lang.String)parameter_InvoiceNo.getValue()); //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = ((java.lang.Integer)parameter_reportType.getValue())==2; //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = !"2".equals(((java.lang.String)parameter_PaymentMethod.getValue())); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = !"2".equals(((java.lang.String)parameter_PaymentMethod.getValue())); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = ((java.lang.String)parameter_InvoiceNo.getValue()); //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = "2".equals(((java.lang.String)parameter_PaymentMethod.getValue())) ? "HKNet accepts payment by VISA or MasterCard only. Each Sim2Travel bill will be charged to the credit card that you have provided.":"HKNet accepts payment via bank wire transfer. The total amount due must be paid in Hong Kong Dollars (HKD) via bank wire transfer. before / on the 25 of the current month. Payment MUST include the full name and bill number. Transfer should be made directly to our billing partner Sim2Travel Inc."; //$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = ((java.util.List)parameter_BS.getValue())!=null && ((java.util.List)parameter_BS.getValue()).size()>0; //$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()); //$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()); //$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = ((java.lang.String)parameter_Statement32for.getValue()); //$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = ((java.lang.String)parameter_imageName.getValue()); //$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = ((java.lang.String)parameter_Billing32Period.getValue()); //$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = ((java.lang.String)parameter_customerServiceNumber.getValue()); //$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = ((java.lang.String)parameter_Currency.getValue()); //$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = new net.sf.jasperreports.engine.data.JRBeanCollectionDataSource(((java.util.List)parameter_BS.getValue())); //$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = ((java.lang.String)parameter_SUBREPORT_DIR.getValue()) + "billreport_detail.jasper"; //$JR_EXPR_ID=59$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
